import type {
  MockUbitsCatalogs,
  MockUbitsDimension,
  MockUbitsQuestion,
  MockUbitsDemographic,
  MockUbitsDemographicValue,
  MockUbitsUser,
  MockUbitsSurveyType,
  MockUbitsAlias,
} from './types';

const now = new Date().toISOString();

const dimensions: MockUbitsDimension[] = [
  {
    id: 'dim_1',
    name: 'Liderazgo',
    canonicalName: 'LIDERAZGO',
    description: 'Evalúa la percepción sobre las habilidades y comportamientos de los líderes.',
    aliases: ['Lider', 'Lideres', 'Leadership'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    questionIds: ['q_1', 'q_2', 'q_3'],
    metadata: { category: 'CORE', isCore: true },
  },
  {
    id: 'dim_2',
    name: 'Comunicación',
    canonicalName: 'COMUNICACION',
    description: 'Flujo de información y claridad en los mensajes dentro de la empresa.',
    aliases: ['Comunicacion', 'Comunicación interna', 'Communication'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    questionIds: ['q_4', 'q_5'],
    metadata: { category: 'CORE', isCore: true },
  },
  {
    id: 'dim_3',
    name: 'Bienestar',
    canonicalName: 'BIENESTAR',
    description: 'Salud física, mental y equilibrio vida-trabajo.',
    aliases: ['Wellness', 'Salud laboral', 'Bienestar laboral'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    questionIds: ['q_6', 'q_7'],
    metadata: { category: 'CORE', isCore: true },
  },
  {
    id: 'dim_4',
    name: 'Desarrollo',
    canonicalName: 'DESARROLLO',
    description: 'Oportunidades de crecimiento profesional y capacitación.',
    aliases: ['Crecimiento', 'Development', 'Capacitación'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    questionIds: ['q_8', 'q_9'],
    metadata: { category: 'CORE', isCore: true },
  },
  {
    id: 'dim_5',
    name: 'Cultura',
    canonicalName: 'CULTURA',
    description: 'Valores, creencias y comportamientos compartidos en la organización.',
    aliases: ['Culture', 'Valores corporativos'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    questionIds: ['q_10', 'q_11'],
    metadata: { category: 'CORE', isCore: true },
  },
  {
    id: 'dim_6',
    name: 'Compromiso',
    canonicalName: 'COMPROMISO',
    description: 'Nivel de conexión emocional y esfuerzo discrecional de los empleados.',
    aliases: ['Engagement', 'Pertenencia'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    questionIds: ['q_12', 'q_13'],
    metadata: { category: 'CORE', isCore: true },
  },
  {
    id: 'dim_7',
    name: 'Reconocimiento',
    canonicalName: 'RECONOCIMIENTO',
    description: 'Valoración del trabajo y aportes de los colaboradores.',
    aliases: ['Recognition', 'Recompensas'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    questionIds: ['q_14', 'q_15'],
    metadata: { category: 'CORE', isCore: true },
  },
  {
    id: 'dim_8',
    name: 'Carga laboral',
    canonicalName: 'CARGA_LABORAL',
    description: 'Percepción sobre el volumen de trabajo y recursos disponibles.',
    aliases: ['Workload', 'Carga de trabajo'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    questionIds: ['q_16'],
    metadata: { category: 'CORE', isCore: true },
  },
];

const questions: MockUbitsQuestion[] = [
  // Liderazgo
  {
    id: 'q_1',
    dimensionId: 'dim_1',
    text: 'Mi líder directo me proporciona retroalimentación constructiva.',
    canonicalText: 'LIDER_RETROALIMENTACION_CONSTRUCTIVA',
    aliases: ['Mi jefe me da buen feedback', 'Recibo feedback útil de mi manager'],
    questionType: 'LIKERT',
    scale: '1_TO_5',
    status: 'ACTIVE',
    recommendedForComparison: true,
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { language: 'es', isReverseScored: false },
  },
  {
    id: 'q_2',
    dimensionId: 'dim_1',
    text: 'Confío en las decisiones de los líderes de la empresa.',
    canonicalText: 'CONFIANZA_DECISIONES_LIDERES',
    aliases: ['Hay confianza en la alta gerencia'],
    questionType: 'LIKERT',
    scale: '1_TO_5',
    status: 'ACTIVE',
    recommendedForComparison: true,
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { language: 'es', isReverseScored: false },
  },
  {
    id: 'q_3',
    dimensionId: 'dim_1',
    text: 'Mi líder fomenta un ambiente de respeto.',
    canonicalText: 'LIDER_AMBIENTE_RESPETO',
    aliases: ['Mi jefe me trata con respeto'],
    questionType: 'LIKERT',
    scale: '1_TO_5',
    status: 'ACTIVE',
    recommendedForComparison: true,
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { language: 'es', isReverseScored: false },
  },
  // Comunicación
  {
    id: 'q_4',
    dimensionId: 'dim_2',
    text: 'La información fluye de manera efectiva entre las áreas.',
    canonicalText: 'COMUNICACION_ENTRE_AREAS',
    aliases: ['Hay buena comunicación entre equipos', 'Las áreas se comunican bien'],
    questionType: 'LIKERT',
    scale: '1_TO_5',
    status: 'ACTIVE',
    recommendedForComparison: true,
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { language: 'es', isReverseScored: false },
  },
  {
    id: 'q_5',
    dimensionId: 'dim_2',
    text: 'Los canales de comunicación interna son adecuados.',
    canonicalText: 'CANALES_COMUNICACION_ADECUADOS',
    aliases: [],
    questionType: 'LIKERT',
    scale: '1_TO_5',
    status: 'ACTIVE',
    recommendedForComparison: true,
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { language: 'es', isReverseScored: false },
  },
  // Bienestar
  {
    id: 'q_6',
    dimensionId: 'dim_3',
    text: 'La empresa se preocupa por mi bienestar físico y mental.',
    canonicalText: 'PREOCUPACION_BIENESTAR_EMPLEADO',
    aliases: ['Siento que le importo a la empresa como persona'],
    questionType: 'LIKERT',
    scale: '1_TO_5',
    status: 'ACTIVE',
    recommendedForComparison: true,
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { language: 'es', isReverseScored: false },
  },
  {
    id: 'q_7',
    dimensionId: 'dim_3',
    text: 'Tengo un buen equilibrio entre mi vida personal y laboral.',
    canonicalText: 'EQUILIBRIO_VIDA_TRABAJO',
    aliases: ['Work life balance es bueno', 'Tengo tiempo para mi familia'],
    questionType: 'LIKERT',
    scale: '1_TO_5',
    status: 'ACTIVE',
    recommendedForComparison: true,
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { language: 'es', isReverseScored: false },
  },
  // Desarrollo
  {
    id: 'q_8',
    dimensionId: 'dim_4',
    text: 'Tengo oportunidades de crecer profesionalmente aquí.',
    canonicalText: 'OPORTUNIDADES_CRECIMIENTO_PROFESIONAL',
    aliases: ['Veo oportunidades de desarrollo', 'Puedo ascender en esta empresa'],
    questionType: 'LIKERT',
    scale: '1_TO_5',
    status: 'ACTIVE',
    recommendedForComparison: true,
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { language: 'es', isReverseScored: false },
  },
  {
    id: 'q_9',
    dimensionId: 'dim_4',
    text: 'Recibo la capacitación necesaria para hacer bien mi trabajo.',
    canonicalText: 'CAPACITACION_ADECUADA_TRABAJO',
    aliases: ['La empresa me entrena bien'],
    questionType: 'LIKERT',
    scale: '1_TO_5',
    status: 'ACTIVE',
    recommendedForComparison: true,
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { language: 'es', isReverseScored: false },
  },
  // Cultura
  {
    id: 'q_10',
    dimensionId: 'dim_5',
    text: 'Me siento alineado con los valores de la empresa.',
    canonicalText: 'ALINEACION_VALORES_EMPRESA',
    aliases: ['Comparto la cultura de la empresa'],
    questionType: 'LIKERT',
    scale: '1_TO_5',
    status: 'ACTIVE',
    recommendedForComparison: true,
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { language: 'es', isReverseScored: false },
  },
  {
    id: 'q_11',
    dimensionId: 'dim_5',
    text: 'Recomendaría esta empresa como un buen lugar para trabajar.',
    canonicalText: 'ENPS_RECOMENDAR_EMPRESA',
    aliases: ['eNPS'],
    questionType: 'NPS',
    scale: '0_TO_10',
    status: 'ACTIVE',
    recommendedForComparison: true,
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { language: 'es', isReverseScored: false },
  },
  // Compromiso
  {
    id: 'q_12',
    dimensionId: 'dim_6',
    text: 'Me siento orgulloso de trabajar en esta organización.',
    canonicalText: 'ORGULLO_TRABAJAR_AQUI',
    aliases: [],
    questionType: 'LIKERT',
    scale: '1_TO_5',
    status: 'ACTIVE',
    recommendedForComparison: true,
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { language: 'es', isReverseScored: false },
  },
  {
    id: 'q_13',
    dimensionId: 'dim_6',
    text: 'Estoy dispuesto a dar un esfuerzo extra cuando la empresa lo necesita.',
    canonicalText: 'DISPOSICION_ESFUERZO_EXTRA',
    aliases: [],
    questionType: 'LIKERT',
    scale: '1_TO_5',
    status: 'ACTIVE',
    recommendedForComparison: true,
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { language: 'es', isReverseScored: false },
  },
  // Reconocimiento
  {
    id: 'q_14',
    dimensionId: 'dim_7',
    text: 'Siento que mi trabajo es valorado por mis compañeros.',
    canonicalText: 'TRABAJO_VALORADO_COMPANEROS',
    aliases: [],
    questionType: 'LIKERT',
    scale: '1_TO_5',
    status: 'ACTIVE',
    recommendedForComparison: true,
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { language: 'es', isReverseScored: false },
  },
  {
    id: 'q_15',
    dimensionId: 'dim_7',
    text: 'Recibo reconocimiento cuando hago un buen trabajo.',
    canonicalText: 'RECONOCIMIENTO_BUEN_TRABAJO',
    aliases: ['Me reconocen cuando hago las cosas bien'],
    questionType: 'LIKERT',
    scale: '1_TO_5',
    status: 'ACTIVE',
    recommendedForComparison: true,
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { language: 'es', isReverseScored: false },
  },
  // Carga laboral
  {
    id: 'q_16',
    dimensionId: 'dim_8',
    text: 'Mi carga de trabajo es manejable en el tiempo establecido.',
    canonicalText: 'CARGA_TRABAJO_MANEJABLE',
    aliases: ['No tengo exceso de trabajo'],
    questionType: 'LIKERT',
    scale: '1_TO_5',
    status: 'ACTIVE',
    recommendedForComparison: true,
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { language: 'es', isReverseScored: false },
  },
  // Custom / No Match
  {
    id: 'q_17',
    dimensionId: null,
    text: '¿Cómo calificarías la calidad del café en la oficina?',
    canonicalText: 'CALIDAD_CAFE_OFICINA',
    aliases: [],
    questionType: 'LIKERT',
    scale: '1_TO_5',
    status: 'ACTIVE',
    recommendedForComparison: false,
    createdAt: now,
    updatedAt: now,
    source: 'CUSTOM',
    metadata: { language: 'es', isReverseScored: false },
  },
];

const demographics: MockUbitsDemographic[] = [
  {
    id: 'demo_1',
    name: 'País',
    canonicalName: 'PAIS',
    aliases: ['PAIS', 'pais', 'País de residencia', 'Country', 'Location country'],
    valueIds: ['val_1', 'val_2', 'val_3', 'val_4', 'val_5'],
    isFilterable: true,
    isRequiredForImport: false,
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { dataType: 'STRING', displayOrder: 1 },
  },
  {
    id: 'demo_2',
    name: 'Área',
    canonicalName: 'AREA',
    aliases: ['Area', 'Departamento', 'Department'],
    valueIds: ['val_6', 'val_7', 'val_8'],
    isFilterable: true,
    isRequiredForImport: false,
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { dataType: 'STRING', displayOrder: 2 },
  },
  {
    id: 'demo_3',
    name: 'Gerencia',
    canonicalName: 'GERENCIA',
    aliases: ['Dirección', 'Management'],
    valueIds: [],
    isFilterable: true,
    isRequiredForImport: false,
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { dataType: 'STRING', displayOrder: 3 },
  },
  {
    id: 'demo_4',
    name: 'Cargo',
    canonicalName: 'CARGO',
    aliases: ['Puesto', 'Job Title', 'Role'],
    valueIds: [],
    isFilterable: true,
    isRequiredForImport: false,
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { dataType: 'STRING', displayOrder: 4 },
  },
  {
    id: 'demo_5',
    name: 'Antigüedad',
    canonicalName: 'ANTIGUEDAD',
    aliases: ['Tenure', 'Tiempo en la empresa'],
    valueIds: [],
    isFilterable: true,
    isRequiredForImport: false,
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { dataType: 'STRING', displayOrder: 5 },
  },
  {
    id: 'demo_6',
    name: 'Sede',
    canonicalName: 'SEDE',
    aliases: ['Oficina', 'Location', 'Site'],
    valueIds: [],
    isFilterable: true,
    isRequiredForImport: false,
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { dataType: 'STRING', displayOrder: 6 },
  },
  {
    id: 'demo_7',
    name: 'Nivel',
    canonicalName: 'NIVEL',
    aliases: ['Level', 'Seniority'],
    valueIds: [],
    isFilterable: true,
    isRequiredForImport: false,
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { dataType: 'STRING', displayOrder: 7 },
  },
  {
    id: 'demo_8',
    name: 'Tipo de contrato',
    canonicalName: 'TIPO_CONTRATO',
    aliases: ['Contract Type', 'Modalidad de contratación'],
    valueIds: [],
    isFilterable: true,
    isRequiredForImport: false,
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { dataType: 'STRING', displayOrder: 8 },
  },
];

const demographicValues: MockUbitsDemographicValue[] = [
  // País values
  {
    id: 'val_1',
    demographicId: 'demo_1',
    name: 'Colombia',
    canonicalName: 'COLOMBIA',
    aliases: ['CO', 'Col', 'República de Colombia'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { isActiveForFiltering: true },
  },
  {
    id: 'val_2',
    demographicId: 'demo_1',
    name: 'México',
    canonicalName: 'MEXICO',
    aliases: ['MX', 'Mexico', 'Mex'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { isActiveForFiltering: true },
  },
  {
    id: 'val_3',
    demographicId: 'demo_1',
    name: 'Perú',
    canonicalName: 'PERU',
    aliases: ['PE', 'Peru'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { isActiveForFiltering: true },
  },
  {
    id: 'val_4',
    demographicId: 'demo_1',
    name: 'Chile',
    canonicalName: 'CHILE',
    aliases: ['CL', 'Chi'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { isActiveForFiltering: true },
  },
  {
    id: 'val_5',
    demographicId: 'demo_1',
    name: 'Argentina',
    canonicalName: 'ARGENTINA',
    aliases: ['AR', 'Arg'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { isActiveForFiltering: true },
  },
  // Área values
  {
    id: 'val_6',
    demographicId: 'demo_2',
    name: 'Tecnología',
    canonicalName: 'TECNOLOGIA',
    aliases: ['Tech', 'IT', 'Sistemas'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { isActiveForFiltering: true },
  },
  {
    id: 'val_7',
    demographicId: 'demo_2',
    name: 'Ventas',
    canonicalName: 'VENTAS',
    aliases: ['Sales', 'Comercial'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { isActiveForFiltering: true },
  },
  {
    id: 'val_8',
    demographicId: 'demo_2',
    name: 'Recursos Humanos',
    canonicalName: 'RECURSOS_HUMANOS',
    aliases: ['HR', 'RRHH', 'People', 'Talento Humano'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { isActiveForFiltering: true },
  },
];

const users: MockUbitsUser[] = [
  {
    id: 'user_1',
    fullName: 'Juan Perez',
    email: 'juan.perez@example.com',
    documentId: '1001001001',
    employeeId: 'EMP001',
    country: 'Colombia',
    status: 'ACTIVE',
    demographicValueIds: ['val_1', 'val_6'],
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { role: 'EMPLOYEE', lastLoginAt: now },
  },
  {
    id: 'user_2',
    fullName: 'Maria Gomez',
    email: 'maria.gomez@example.org',
    documentId: '2002002002',
    employeeId: 'EMP002',
    country: 'México',
    status: 'ACTIVE',
    demographicValueIds: ['val_2', 'val_7'],
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { role: 'MANAGER', lastLoginAt: now },
  },
  {
    id: 'user_3',
    fullName: 'Carlos Ruiz',
    email: 'carlos.ruiz@example.com',
    documentId: null,
    employeeId: 'EMP003',
    country: 'Perú',
    status: 'INACTIVE',
    demographicValueIds: ['val_3', 'val_8'],
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { role: 'EMPLOYEE', lastLoginAt: null },
  },
  {
    id: 'user_4',
    fullName: 'Ana Torres',
    email: null,
    documentId: '4004004004',
    employeeId: null,
    country: 'Chile',
    status: 'ACTIVE',
    demographicValueIds: ['val_4', 'val_6'],
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { role: 'EMPLOYEE', lastLoginAt: now },
  },
  {
    id: 'user_5',
    fullName: 'Luisa Martinez',
    email: 'luisa.m@example.com',
    documentId: '5005005005',
    employeeId: 'EMP005',
    country: 'Argentina',
    status: 'ACTIVE',
    demographicValueIds: ['val_5', 'val_7'],
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { role: 'EMPLOYEE', lastLoginAt: now },
  },
];

const surveyTypes: MockUbitsSurveyType[] = [
  {
    id: 'st_1',
    name: 'Clima',
    aliases: ['Clima laboral', 'Workplace Climate'],
    defaultScale: '1_TO_5',
    supportedComparisonModes: ['BENCHMARK', 'INTERNAL_NORM', 'TREND'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { isAnonymousByDefault: true, frequencyHint: 'ANNUAL' },
  },
  {
    id: 'st_2',
    name: 'Pulso',
    aliases: ['Pulse', 'Encuesta de pulso'],
    defaultScale: '1_TO_5',
    supportedComparisonModes: ['TREND'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { isAnonymousByDefault: true, frequencyHint: 'MONTHLY' },
  },
  {
    id: 'st_3',
    name: 'Engagement',
    aliases: ['Compromiso', 'Employee Engagement'],
    defaultScale: '1_TO_5',
    supportedComparisonModes: ['BENCHMARK', 'INTERNAL_NORM', 'TREND'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { isAnonymousByDefault: true, frequencyHint: 'BIANNUAL' },
  },
  {
    id: 'st_4',
    name: 'NPS',
    aliases: ['eNPS', 'Net Promoter Score'],
    defaultScale: '0_TO_10',
    supportedComparisonModes: ['BENCHMARK', 'TREND'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { isAnonymousByDefault: true, frequencyHint: 'QUARTERLY' },
  },
  {
    id: 'st_5',
    name: 'Liderazgo',
    aliases: ['Leadership Assessment', 'Evaluación de líderes'],
    defaultScale: '1_TO_5',
    supportedComparisonModes: ['INTERNAL_NORM', 'TREND'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { isAnonymousByDefault: false, frequencyHint: 'ANNUAL' },
  },
  {
    id: 'st_6',
    name: 'Bienestar',
    aliases: ['Wellness', 'Salud Organizacional'],
    defaultScale: '1_TO_5',
    supportedComparisonModes: ['BENCHMARK', 'TREND'],
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
    source: 'SYSTEM',
    metadata: { isAnonymousByDefault: true, frequencyHint: 'BIANNUAL' },
  },
];

const aliases: MockUbitsAlias[] = [
  {
    id: 'alias_1',
    sourceText: 'PAIS',
    normalizedText: 'País',
    targetEntityType: 'DEMOGRAPHIC',
    targetEntityId: 'demo_1',
    matchMethodHint: 'EXACT',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'alias_2',
    sourceText: 'Country',
    normalizedText: 'País',
    targetEntityType: 'DEMOGRAPHIC',
    targetEntityId: 'demo_1',
    matchMethodHint: 'SYNONYM',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'alias_3',
    sourceText: 'Comunicacion',
    normalizedText: 'Comunicación',
    targetEntityType: 'DIMENSION',
    targetEntityId: 'dim_2',
    matchMethodHint: 'EXACT',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'alias_4',
    sourceText: 'Leadership',
    normalizedText: 'Liderazgo',
    targetEntityType: 'DIMENSION',
    targetEntityId: 'dim_1',
    matchMethodHint: 'SYNONYM',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'alias_5',
    sourceText: 'Wellness',
    normalizedText: 'Bienestar',
    targetEntityType: 'DIMENSION',
    targetEntityId: 'dim_3',
    matchMethodHint: 'SYNONYM',
    createdAt: now,
    updatedAt: now,
  },
];

export const mockUbitsCatalogs: MockUbitsCatalogs = {
  dimensions,
  questions,
  demographics,
  demographicValues,
  users,
  surveyTypes,
  aliases,
};
